#!/bin/bash

# switch to environment JVM as needed
JAVA_HOME=/usr

EVO=lib/evosuite-master-1.0.7-SNAPSHOT.jar
TOOL=lib/runtool-1.0.jar

java -cp .:$EVO:$TOOL -Dlogback.configurationFile=/home/evosuite_4th/sbst_logback.xml  -Duse_different_logback=sbst_logback.xml  sbst.runtool.Main  