#!/bin/bash

EVO=lib/evosuite-master-1.0.3-SNAPSHOT.jar
TOOL=lib/runtool-1.0.jar

java -cp .:$EVO:$TOOL -Dlogback.configurationFile=/home/evosuite_4th/sbst_logback.xml  -Duse_different_logback=sbst_logback.xml  sbst.runtool.Main  