#!/bin/bash

EVO=lib/evosuite-master-0.1.1-SNAPSHOT-jar-minimal.jar
TOOL=lib/runtool-1.0.jar

java -cp .:$EVO:$TOOL -Dlogback.configurationFile=/home/evosuite_3rd/sbst_logback.xml  -Duse_different_logback=sbst_logback.xml  sbst.runtool.Main  